<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>My site!</title>
	<meta name="app_version" content="<?= \App\Config::getVersion() ?>">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<!--[if IE]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?= \Koldy\Route::asset('css/main.css') ?>"/>
</head>
<body>

<div class="container mt-4">
	<div class="col-md-12">
		<div class="jumbotron page">
      <?= $this->renderViewInKeyIf('page') ?>
		</div>
	</div>
</div>

<?= $this->render('elements/browser-update') ?>
</body>
</html>