<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>My site!</title>
	<meta name="app_version" content="<?= \App\Config::getVersion() ?>">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<!--[if IE]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?= \Koldy\Route::asset('css/main.css') ?>"/>
</head>
<body>

<div class="container mt-4">
	<div class="col-md-12">
		<div class="jumbotron page">
      <?= $this->renderViewInKeyIf('page') ?>
		</div>
	</div>
</div>

<div class="container mt-4">
	<div class="row">
		<div class="col-md-6">
			<div class="alert alert-primary">See some local examples</div>
			<ul>
				<li><a href="<?= \Koldy\Route::href('maintenance') ?>">Maintenance page</a></li>
				<li><a href="<?= \Koldy\Route::href('dev') ?>">Dev module route</a></li>
				<li><a href="<?= \Koldy\Route::href('json') ?>">Json response example</a> or <a href="<?= \Koldy\Route::href('index', 'json') ?>">alternative route</a></li>
				<li><a href="<?= \Koldy\Route::href('robots.txt') ?>">See robots.txt</a></li>
				<li><a href="<?= \Koldy\Route::href('test-exception') ?>">Test exception</a></li>
				<li><a href="<?= \Koldy\Route::href('test-error') ?>">Test error logging</a></li>
			</ul>
			<div class="alert alert-primary">Next steps</div>
			<ul>
				<li>get familiar with <a href="https://www.vagrantup.com/intro/index.html" target="_blank">Vagrant</a></li>
				<li>review provision.sh and chosen databases</li>
				<li>review Vagrantfile and chosen ports</li>
				<li><a href="https://koldy.net/framework/docs/2.0/database/migrations.md#creating-migration" target="_blank">create your first migration</a></li>
				<li>create your own database model</li>
				<li>create your own controller, view and use database model</li>
			</ul>
		</div>
		<div class="col-md-6">
			<div class="alert alert-primary">About database</div>
			<p>
				Both MySQL (MariaDB) and PostgreSQL are installed on your Vagrant machine as an example. To connect to database, use the following
				credentials for both databases:
			</p>
			<ul>
				<li>host: <code>localhost</code></li>
				<li>username: <code>vagrant</code></li>
				<li>password: <code>vagrant</code></li>
				<li>database: <code>vagrant</code></li>
				<li>port: <code>5001</code> for MySQL and <code>5002</code> for PostgreSQL</li>
			</ul>
		</div>
	</div>
</div>

<?= $this->render('elements/browser-update') ?>
</body>
</html>